### ISSUE TITLE
Switch OmicsIntegrator from CC BY-NC to an open source license

### ISSUE THREAD

**Issue by dhimmel** [fraenkel-lab/OmicsIntegrator#11]
OmicsIntegrator was originally licensed under an MIT license, which is an open source license. However, MIT officials switched it to CC BY-NC?

[![OmicsIntegrator LICENSE history](https://cloud.githubusercontent.com/assets/1117703/14939455/94e70ad6-0efc-11e6-87f2-5ca29d043ac5.png)](https://github.com/fraenkel-lab/OmicsIntegrator/commits/master/LICENSE)

Unfortunately, the non-commercial stipulation violates the [Open Source Definition](https://opensource.org/osd.html). Specifically, it violates criterion 6 which states:

> **No Discrimination Against Fields of Endeavor:** The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.
> _**Rationale:** The major intention of this clause is to prohibit license traps that prevent open source from being used commercially. We want commercial users to join our community, not feel excluded from it._

Indeed, _PLOS Computational Biology_, where this project was [published](https://doi.org/10.1371/journal.pcbi.1004879), states in its [policy for software papers](http://journals.plos.org/ploscompbiol/s/submission-guidelines#loc-software-submissions):

> The software must be downloadable anonymously in source code form and licensed under an [Open Source Initiative (OSI) compliant license](http://www.opensource.org/licenses/alphabetical).

CC BY-NC is not an OSI approved license. It's worth noting that the [ambiguity of commercial usage](https://doi.org/10.3897/zookeys.150.2189) makes NC stipulations especially toxic. Additionally, Creative Commons licenses (excluding CC0) are [not recommended](https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F) for software.

According to the publication funding statement:

> This work was supported by NIH grants U54CA112967, U01CA184898 U54NS091046, R01GM089903 and used computing resources supported by the National Science Foundation under Award No. DBI-0821391.

If the change to a CC BY-NC license was required by the MIT legal department, I'd love to hear their justification for restricting reuse of publicly-funded research.

**Comment by sgosline** [comment]
@AmandaKedaigle Can you comment on this? I'm curious as well.

**Comment by AmandaKedaigle** [comment]
We are in touch with the MIT TLO to figure this out

**Comment by AmandaKedaigle** [comment]
Thank you for your interest in our software, and for bringing this licensing issue to our attention. We have scheduled a meeting with MIT's Liscensing Office to review the issue and will update the license after that meeting to make it fully compliant with all PLOS and NIH requirements.

**Comment by AmandaKedaigle** [comment]
Updated to BSD Open Source license

**Comment by dhimmel** [comment]
Got it! Closed in 94fee38b1aacb14813fb37fd74fa3eefd7d07e4d.

Thanks for addressing the issue. Out of curiosity, how much time did you have to spend to choose a new license and get it approved? And were there any obstacles or parts to the process that could be optimized?
