### ISSUE TITLE
building msgsteiner on Mac OS requires gcc

### ISSUE THREAD

**Issue by koksal** [fraenkel-lab/OmicsIntegrator#22]
Hi,

I'd like to give some feedback on installation instructions after having successfully run OmicsIntegrator on OS X El Capitan (10.11).

The issue is that on OS X, `gcc` is actually an alias for the Mac version of the `clang` compiler, which doesn't support OpenMP. Meanwhile, msgsteiner requires OpenMP support. I found the solution to be as follows:

1. Install the gcc compiler using homebrew: 
```brew install gcc```
When installed, the compiler can be accessed via the `gcc-6` command.

2. Build the Boost library using homebrew, specifying `gcc-6` as the compiler:
```brew install boost --cc=gcc-6```
Without this extra argument, the library will not be visible to gcc when building msgsteiner.

3. Similarly to the other patches, change the msgsteiner `Makefile` to use `gcc-6` instead of `gcc`.

I wanted to contribute this piece of information since I spent a fair bit of time making sure msgsteiner could be built using Boost :)

**Comment by AmandaKedaigle** [comment]
Thank you for this!

**Comment by AmandaKedaigle** [comment]
Thanks Ali, this worked for me as well! We now link to this thread in our readme.

Notes for future users:

- Step 1 may take quite a bit of time
- In step 3, when editing the msgsteiner `Makefile`, change `g++` to `g++-6`. 
- You may also need to add `-L` and `-I` flags pointed to your installation of boost. In my case, that meant changing the line starting with `LDFLAGS` to `LDFLAGS=-lboost_program_options -lgomp -I /usr/local/Cellar/boost/1.62.0/include/ -L /usr/local/Cellar/boost/1.62.0/lib`

**Comment by koksal** [comment]
Thanks @AmandaKedaigle !

**Comment by agitter** [comment]
Thanks @koksal for the advice.  Commit 1a854b5620954373cec435cfb01f36029f1cd9f9 adds a link to this advice to the readme.
