### ISSUE TITLE
Old versions of example data

### ISSUE THREAD

**Issue by agitter** [fraenkel-lab/OmicsIntegrator#23]
The old versions of the example data files do not need to be tracked in the repository and unnecessarily impact the storage quote.  These can be removed using https://rtyley.github.io/bfg-repo-cleaner/

**Comment by sgosline** [comment]
This appears to be impossible with LFS.  See https://github.com/github/git-lfs/issues/1101.  I think we should re-open if I am wrong or can find another solution...

**Comment by scher200** [comment]
I agree, i would really like to delete old git-lfs stored files from repo's
