### ISSUE TITLE
Garnet motif gif indices

### ISSUE THREAD

**Issue by agitter** [fraenkel-lab/OmicsIntegrator#5]
There may be a mismatch between the motif indices and the motif gif indices when using the IC8 set of motifs.  The motif gif files range from `motif0.gif` to `motif518.gif` where the index appears to be derived from the motif's line number in `vertebrates_clustered_motifs_tfids.txt`.  However, when running Garnet with the IC8 motifs, the line numbers in `vertebrates_clustered_ic8_motifs_tfids.txt` are different and map to the incorrect motif gif.

**Comment by sgosline** [comment]
Good catch. I've generated a new set of GIF files. I haven't checked it in yet because there are some other issues with the time-reduction step that I've also implemented (moving across country mid-fix was not wise!).

**Comment by sgosline** [comment]
@agitter I'm just reviewing issues and I believe this has been resolved, can you verify and close?

**Comment by agitter** [comment]
The student who discovered this is no longer available to rerun his example, and I'm not sure that I recall all of the details of the problem.  If you pushed a fix, we can close the issue.
